/*
 * DO NOT EDIT THIS FILE. Generated by checkmk.
 * Edit the original source file "test.check" instead.
 */

#include <check.h>

#line 1 "test.check"
#include <stdio.h>
#include <string.h>

#include "../s21_string.h"

START_TEST(test_s21_memchr) {
#line 6
  const char hello_str[] = "Hello world";
  const char empty_str[] = "\0";
  char match = 'l';
  char no_match = 'x';
  size_t n = 5, m = 1;
#ifdef __APPLE__
  size_t k = 7;
  const char line_break[] = "\n\0";
  const char letter_with_l_break[] = "a\n\0";
#endif
  ck_assert_ptr_eq(s21_memchr(hello_str, match, n),
                   memchr(hello_str, match, n));
  ck_assert_ptr_null(s21_memchr(hello_str, no_match, n));
  ck_assert_ptr_null(s21_memchr(empty_str, no_match, m));
#ifdef __APPLE__
  ck_assert_ptr_eq(s21_memchr(letter_with_l_break, 'a', k),
                   memchr(letter_with_l_break, 'a', k));
  ck_assert_ptr_eq(s21_memchr(line_break, 'a', k), memchr(line_break, 'a', k));
#endif
}
END_TEST

START_TEST(test_s21_memcmp) {
#line 25
  const char hello_str[] = "Hello world";
  const char school_str[] = "School 21";
  int n = 10;
  ck_assert_int_eq(s21_memcmp(hello_str, hello_str, n),
                   memcmp(hello_str, hello_str, n));
  ck_assert_int_eq(s21_memcmp(hello_str, school_str, n),
                   memcmp(hello_str, school_str, n));
#ifdef __APPLE__
  const char space_str[] = " \0";
  const char empty_str[] = "\0";
  ck_assert_int_eq(s21_memcmp(hello_str, empty_str, n),
                   memcmp(hello_str, empty_str, n));
  ck_assert_int_eq(s21_memcmp(empty_str, empty_str, n),
                   memcmp(empty_str, empty_str, n));
  ck_assert_int_eq(s21_memcmp(space_str, hello_str, n),
                   memcmp(space_str, hello_str, n));
#endif
  ck_assert_int_eq(s21_memcmp(hello_str, school_str, 0),
                   memcmp(hello_str, school_str, 0));
}
END_TEST

START_TEST(test_s21_memcpy) {
#line 40
  const char hello_str[] = "Hello world";
  const char school_str[] = "School 21";
  const char letter_with_l_break[] = "a\n\0";
  const char space_str[] = " \0";
  const char line_break[] = "\n\0";
  const char empty_str[] = "\0";
  const char src[] = {'a', 'b', '\0', 'c'};
  int a = 0, b = 5;
  char dest[20] = {'\0'};
  char control_dest[20] = {'\0'};
  ck_assert_str_eq(s21_memcpy(dest, src, 4), memcpy(control_dest, src, 4));
  ck_assert_int_eq(dest[3], control_dest[3]);
  ck_assert_str_eq(s21_memcpy(dest, hello_str, b),
                   memcpy(control_dest, hello_str, b));
  ck_assert_str_eq(s21_memcpy(dest, school_str, a),
                   memcpy(control_dest, school_str, a));
  ck_assert_str_eq(s21_memcpy(dest, empty_str, 1),
                   memcpy(control_dest, empty_str, 1));
  ck_assert_str_eq(s21_memcpy(dest, letter_with_l_break, 2),
                   memcpy(control_dest, letter_with_l_break, 2));
  ck_assert_str_ne(s21_memcpy(dest, space_str, 2),
                   memcpy(control_dest, line_break, 2));
}
END_TEST

START_TEST(test_s21_memset) {
#line 59
  size_t a = 0, b = 5;
  char symb = 'x';
  char dest[10] = {'\0'};
  char control_dest[10] = {'\0'};
  ck_assert_str_eq(s21_memset(dest, symb, a), memset(control_dest, symb, a));
  ck_assert_str_eq(s21_memset(dest, symb, b), memset(control_dest, symb, b));
}
END_TEST

START_TEST(test_s21_strncat) {
#line 67
  size_t n = 5, a = 0, b = 15;
  char dest[20] = {'\0'};
  char control_dest[20] = {'\0'};
  const char empty_str[] = "\0";
  const char school_str[] = "School 21";
  const char line_break[] = "\n\0";
  ck_assert_str_eq(s21_strncat(dest, empty_str, n),
                   strncat(control_dest, empty_str, n));
  ck_assert_str_eq(s21_strncat(dest, school_str, b),
                   strncat(control_dest, school_str, b));
  ck_assert_str_eq(s21_strncat(dest, empty_str, n),
                   strncat(control_dest, empty_str, n));
  ck_assert_str_eq(s21_strncat(dest, school_str, n),
                   strncat(control_dest, school_str, n));
  ck_assert_str_eq(s21_strncat(dest, school_str, a),
                   strncat(control_dest, school_str, a));
  ck_assert_str_eq(s21_strncat(dest, line_break, n),
                   strncat(control_dest, line_break, n));
}
END_TEST

START_TEST(test_s21_strchr) {
#line 81
  char first = 'S';
  char last = '1';
  char not_match = 'x';
  char l_break = '\n';
  char null_ch = '\0';
  const char school_str[] = "School 21";
  const char empty_str[] = "\0";
  const char line_break[] = "\n\0";
  ck_assert_ptr_eq(s21_strchr(school_str, first), strchr(school_str, first));
  ck_assert_ptr_eq(s21_strchr(school_str, last), strchr(school_str, last));
  ck_assert_ptr_eq(s21_strchr(school_str, not_match),
                   strchr(school_str, not_match));
  ck_assert_ptr_eq(s21_strchr(line_break, l_break),
                   strchr(line_break, l_break));
  ck_assert_ptr_eq(s21_strchr(empty_str, not_match),
                   strchr(empty_str, not_match));
  ck_assert_ptr_eq(s21_strchr(school_str, null_ch),
                   strchr(school_str, null_ch));
}
END_TEST

START_TEST(test_s21_strncmp) {
#line 97
  size_t a = 0, b = 5, c = 15;
  const char school_str[] = "School 21";
  const char empty_str[] = "\0";
  const char hello_str[] = "Hello world";
  ck_assert_int_eq(s21_strncmp(school_str, school_str, b),
                   strncmp(school_str, school_str, b));
  ck_assert_int_eq(s21_strncmp(school_str, school_str, a),
                   strncmp(school_str, school_str, a));
  ck_assert_int_eq(s21_strncmp(school_str, school_str, c),
                   strncmp(school_str, school_str, c));
  ck_assert_int_eq(s21_strncmp(school_str, hello_str, b),
                   strncmp(school_str, hello_str, b));
  ck_assert_int_eq(s21_strncmp(empty_str, empty_str, b),
                   strncmp(empty_str, empty_str, b));
  ck_assert_int_eq(s21_strncmp(school_str, empty_str, b),
                   strncmp(school_str, empty_str, b));
  ck_assert_int_eq(s21_strncmp(school_str, empty_str, a),
                   strncmp(school_str, empty_str, a));
#ifdef __APPLE__
  const char line_break[] = "\n\0";
  const char space_str[] = " \0";
  ck_assert_int_eq(s21_strncmp(line_break, line_break, b),
                   strncmp(line_break, line_break, b));
  ck_assert_int_eq(s21_strncmp(space_str, line_break, b),
                   strncmp(space_str, line_break, b));
#endif
}
END_TEST

START_TEST(test_s21_strncpy) {
#line 116
  const char hello_str[] = "Hello world";
  const char school_str[] = "School 21";
  const char letter_with_l_break[] = "a\n\0";
  const char space_str[] = " \0";
  const char line_break[] = "\n\0";
  const char empty_str[] = "\0";
  size_t a = 0, b = 5;
  char dest[30] = {'\0'};
  char control_dest[30] = {'\0'};
  ck_assert_str_eq(s21_strncpy(dest, hello_str, b),
                   strncpy(control_dest, hello_str, b));
  ck_assert_str_eq(s21_strncpy(dest, school_str, a),
                   strncpy(control_dest, school_str, a));
  ck_assert_str_eq(s21_strncpy(dest, empty_str, b),
                   strncpy(control_dest, empty_str, b));
  ck_assert_str_eq(s21_strncpy(dest, letter_with_l_break, b),
                   strncpy(control_dest, letter_with_l_break, b));
  ck_assert_str_ne(s21_strncpy(dest, space_str, b),
                   strncpy(control_dest, line_break, b));
}
END_TEST

START_TEST(test_s21_strcspn) {
#line 132
  const char school_str[] = "School 21";
  const char hello_str[] = "Hello world";
  const char empty_str[] = "\0";
  const char letter_with_l_break[] = "a\n\0";
  const char space_with_l_break[] = " \n\0";
  ck_assert_int_eq(s21_strcspn(school_str, hello_str),
                   strcspn(school_str, hello_str));
  ck_assert_int_eq(s21_strcspn(hello_str, school_str),
                   strcspn(hello_str, school_str));
  ck_assert_int_eq(s21_strcspn(hello_str, empty_str),
                   strcspn(hello_str, empty_str));
  ck_assert_int_eq(s21_strcspn(empty_str, hello_str),
                   strcspn(empty_str, hello_str));
  ck_assert_int_eq(s21_strcspn(letter_with_l_break, space_with_l_break),
                   strcspn(letter_with_l_break, space_with_l_break));
}
END_TEST

START_TEST(test_s21_strlen) {
#line 144
  const char hello_str[] = "Hello world";
  const char str_with_l_break[] = "Hello world\n\0";
  const char letter_with_l_break[] = "a\n\0";
  const char space_with_l_break[] = " \n\0";
  const char empty_str[] = "\0";
  ck_assert_int_eq(s21_strlen(hello_str), strlen(hello_str));
  ck_assert_int_eq(s21_strlen(str_with_l_break), strlen(str_with_l_break));
  ck_assert_int_eq(s21_strlen(letter_with_l_break),
                   strlen(letter_with_l_break));
  ck_assert_int_eq(s21_strlen(space_with_l_break), strlen(space_with_l_break));
  ck_assert_int_eq(s21_strlen(empty_str), strlen(empty_str));
}
END_TEST

START_TEST(test_s21_strerror) {
#line 156
  ck_assert_str_eq(s21_strerror(20), strerror(20));
  ck_assert_str_eq(s21_strerror(50), strerror(50));
  ck_assert_str_eq(s21_strerror(1000), strerror(1000));
  ck_assert_str_eq(s21_strerror(-10), strerror(-10));
}
END_TEST

START_TEST(test_s21_strpbrk) {
#line 162
  const char hello_str[] = "Hello world";
  const char school_str[] = "School 21";
  const char str[] = "abcfg";
  const char space_str[] = " \0";
  const char empty_str[] = "\0";
  ck_assert_ptr_eq(s21_strpbrk(hello_str, school_str),
                   strpbrk(hello_str, school_str));
  ck_assert_ptr_eq(s21_strpbrk(school_str, hello_str),
                   strpbrk(school_str, hello_str));
  ck_assert_ptr_eq(s21_strpbrk(hello_str, str), strpbrk(hello_str, str));
  ck_assert_ptr_eq(s21_strpbrk(hello_str, empty_str),
                   strpbrk(hello_str, empty_str));
  ck_assert_ptr_eq(s21_strpbrk(empty_str, hello_str),
                   strpbrk(empty_str, hello_str));
  ck_assert_ptr_eq(s21_strpbrk(empty_str, empty_str),
                   strpbrk(empty_str, empty_str));
  ck_assert_ptr_eq(s21_strpbrk(hello_str, hello_str),
                   strpbrk(hello_str, hello_str));
  ck_assert_ptr_eq(s21_strpbrk(hello_str, space_str),
                   strpbrk(hello_str, space_str));
}
END_TEST

START_TEST(test_s21_strrchr) {
#line 177
  const char hello_str[] = "Hello world";
  const char empty_str[] = "\0";
  char last = 'd';
  char first = 'H';
  char middle = 'o';
  char not_match = 'x';
  char null_ch = '\0';
  ck_assert_ptr_eq(s21_strrchr(hello_str, last), strrchr(hello_str, last));
  ck_assert_ptr_eq(s21_strrchr(hello_str, first), strrchr(hello_str, first));
  ck_assert_ptr_eq(s21_strrchr(hello_str, middle), strrchr(hello_str, middle));
  ck_assert_ptr_eq(s21_strrchr(hello_str, not_match),
                   strrchr(hello_str, not_match));
  ck_assert_ptr_eq(s21_strrchr(hello_str, null_ch),
                   strrchr(hello_str, null_ch));
  ck_assert_ptr_eq(s21_strrchr(empty_str, not_match),
                   strrchr(empty_str, not_match));
  ck_assert_ptr_eq(s21_strrchr(empty_str, null_ch),
                   strrchr(empty_str, null_ch));
}
END_TEST

START_TEST(test_s21_strstr) {
#line 193
  const char hello_str[] = "hello whenorlohekdkhexsjdf";
  const char needle[] = "hex";
  const char not_match[] = "not";
  const char many_match[] = "lo";
  const char one_letter[] = "o";
  const char empty_str[] = "\0";
  ck_assert_ptr_eq(s21_strstr(hello_str, needle), strstr(hello_str, needle));
  ck_assert_ptr_eq(s21_strstr(hello_str, not_match),
                   strstr(hello_str, not_match));
  ck_assert_ptr_eq(s21_strstr(hello_str, many_match),
                   strstr(hello_str, many_match));
  ck_assert_ptr_eq(s21_strstr(hello_str, one_letter),
                   strstr(hello_str, one_letter));
  ck_assert_ptr_eq(s21_strstr(hello_str, empty_str),
                   strstr(hello_str, empty_str));
  ck_assert_ptr_eq(s21_strstr(empty_str, empty_str),
                   strstr(empty_str, empty_str));
  ck_assert_ptr_eq(s21_strstr(empty_str, not_match),
                   strstr(empty_str, not_match));
  ck_assert_ptr_eq(s21_strstr(needle, needle), strstr(needle, needle));
}
END_TEST

START_TEST(test_s21_strtok_normal) {
#line 209
  char test_str[] = "one two three four";
  char test_control_str[] = "one two three four";
  char delim[] = " ";
  char *item = s21_strtok(test_str, delim);
  char *control_item = strtok(test_control_str, delim);
  int flag_in_cycle = 0;
  while (item != S21_NULL && control_item != S21_NULL) {
    flag_in_cycle = 1;
    ck_assert_str_eq(item, control_item);
    item = s21_strtok(S21_NULL, delim);
    control_item = strtok(S21_NULL, delim);
  }
  ck_assert_ptr_eq(item, control_item);
  ck_assert_int_eq(flag_in_cycle, 1);
}
END_TEST

START_TEST(test_s21_strtok_empty_delim) {
#line 225
  char test_str[] = "one two three four";
  char test_control_str[] = "one two three four";
  char delim[] = "";
  char *item = s21_strtok(test_str, delim);
  char *control_item = strtok(test_control_str, delim);
  int flag_in_cycle = 0;
  while (item != S21_NULL && control_item != S21_NULL) {
    flag_in_cycle = 1;
    ck_assert_str_eq(item, control_item);
    item = s21_strtok(S21_NULL, delim);
    control_item = strtok(S21_NULL, delim);
  }
  ck_assert_ptr_eq(item, control_item);
  ck_assert_int_eq(flag_in_cycle, 1);
}
END_TEST

START_TEST(test_s21_strtok_empty_str) {
#line 241
  char test_str[] = "";
  char test_control_str[] = "";
  char delim[] = " ";
  char *item = s21_strtok(test_str, delim);
  char *control_item = strtok(test_control_str, delim);
  int flag_in_cycle = 0;
  while (item != S21_NULL && control_item != S21_NULL) {
    flag_in_cycle = 1;
    ck_assert_str_eq(item, control_item);
    item = s21_strtok(S21_NULL, delim);
    control_item = strtok(S21_NULL, delim);
  }
  ck_assert_ptr_eq(item, control_item);
  ck_assert_int_eq(flag_in_cycle, 0);
}
END_TEST

START_TEST(test_s21_strtok_delim_in_end) {
#line 257
  char test_str[] = "abcd cd/";
  char test_control_str[] = "abcd cd/";
  char delim[] = "/";
  char *item = s21_strtok(test_str, delim);
  char *control_item = strtok(test_control_str, delim);
  int flag_in_cycle = 0;
  while (item != S21_NULL && control_item != S21_NULL) {
    flag_in_cycle = 1;
    ck_assert_str_eq(item, control_item);
    item = s21_strtok(S21_NULL, delim);
    control_item = strtok(S21_NULL, delim);
  }
  ck_assert_ptr_eq(item, control_item);
  ck_assert_int_eq(flag_in_cycle, 1);
}
END_TEST

START_TEST(test_s21_strtok_delim_in_start) {
#line 273
  char test_str[] = "/abcd cd";
  char test_control_str[] = "/abcd cd";
  char delim[] = "/";
  char *item = s21_strtok(test_str, delim);
  char *control_item = strtok(test_control_str, delim);
  int flag_in_cycle = 0;
  while (item != S21_NULL && control_item != S21_NULL) {
    flag_in_cycle = 1;
    ck_assert_str_eq(item, control_item);
    item = s21_strtok(S21_NULL, delim);
    control_item = strtok(S21_NULL, delim);
  }
  ck_assert_ptr_eq(item, control_item);
  ck_assert_int_eq(flag_in_cycle, 1);
}
END_TEST

START_TEST(test_s21_strtok_delim_not_match) {
#line 289
  char test_str[] = "/abcd cd kljfg";
  char test_control_str[] = "/abcd cd kljfg";
  char delim[] = "x";
  char *item = s21_strtok(test_str, delim);
  char *control_item = strtok(test_control_str, delim);
  int flag_in_cycle = 0;
  while (item != S21_NULL && control_item != S21_NULL) {
    flag_in_cycle = 1;
    ck_assert_str_eq(item, control_item);
    item = s21_strtok(S21_NULL, delim);
    control_item = strtok(S21_NULL, delim);
  }
  ck_assert_ptr_eq(item, control_item);
  ck_assert_int_eq(flag_in_cycle, 1);
}
END_TEST

START_TEST(test_s21_to_upper) {
#line 305
  char *res = S21_NULL;
  char *str_1 = "abc123 AbC";
  char *str_2 = S21_NULL;
  res = s21_to_upper(str_1);
  ck_assert_str_eq(res, "ABC123 ABC");
  free(res);
  res = s21_to_upper(str_2);
  ck_assert_ptr_eq(res, S21_NULL);
  if (res != S21_NULL) free(res);
}
END_TEST

START_TEST(test_s21_to_lower) {
#line 316
  char *res = S21_NULL;
  char *str_1 = "ABC123 abC";
  char *str_2 = S21_NULL;
  res = s21_to_lower(str_1);
  ck_assert_str_eq(res, "abc123 abc");
  if (res != S21_NULL) free(res);
  res = s21_to_upper(str_2);
  ck_assert_ptr_eq(res, S21_NULL);
  if (res != S21_NULL) free(res);
}
END_TEST

START_TEST(test_s21_insert) {
#line 327
  char *str_1 = "This is test text";
  char *str_2 = "the best ";
  char *res = s21_insert(str_1, str_2, 8);
  ck_assert_str_eq(res, "This is the best test text");
  if (res != S21_NULL) free(res);
  char *str_3 = S21_NULL;
  res = s21_insert(str_3, str_2, 8);
  if (res != S21_NULL) free(res);
}
END_TEST

START_TEST(test_s21_trim) {
#line 337
  const char trim_chars_1[] = " ";
  const char trim_chars_2[] = " !";
  const char str_1[] = " !Hello school21 !";
  char *str_2 = S21_NULL;
  char *res = s21_trim(str_1, trim_chars_1);
  ck_assert_str_eq(res, "!Hello school21 !");
  if (res != S21_NULL) free(res);
  res = s21_trim(str_1, trim_chars_2);
  ck_assert_str_eq(res, "Hello school21");
  if (res != S21_NULL) free(res);
  res = s21_trim(str_2, trim_chars_1);
  ck_assert_ptr_eq(res, S21_NULL);
  if (res != S21_NULL) free(res);
}
END_TEST

START_TEST(test_s21_sprinf_percent) {
#line 352
  char str[100];
  char test_str[100];
  const char format[] = "|This is result: %%|";
  ck_assert_int_eq(s21_sprintf(str, format), sprintf(test_str, format));
  ck_assert_str_eq(str, test_str);
}
END_TEST

START_TEST(test_s21_sprintf_only_c) {
#line 359
  char str[100];
  char test_str[100];
  const char format[] = "|This is result: %c|";
  char c = 'x';
  ck_assert_int_eq(s21_sprintf(str, format, c), sprintf(test_str, format, c));
  ck_assert_str_eq(str, test_str);
}
END_TEST

START_TEST(test_s21_sprintf_c_with_minus) {
#line 367
  char str[100];
  char test_str[100];
  const char format[] = "|This is result: %-c|";
  char c = 'x';
  ck_assert_int_eq(s21_sprintf(str, format, c), sprintf(test_str, format, c));
  ck_assert_str_eq(str, test_str);
}
END_TEST

START_TEST(test_s21_sprintf_c_indentation_space_plus) {
#line 376
  char str[100];
  char test_str[100];
  const char format[] = "|This is result: %10c|";
  char c = 'x';
  ck_assert_int_eq(s21_sprintf(str, format, c), sprintf(test_str, format, c));
  ck_assert_str_eq(str, test_str);
}
END_TEST

START_TEST(test_s21_sprintf_c_indentation_space_minus) {
#line 384
  char str[100];
  char test_str[100];
  const char format[] = "|This is result: %-10c|";
  char c = 'x';
  ck_assert_int_eq(s21_sprintf(str, format, c), sprintf(test_str, format, c));
  ck_assert_str_eq(str, test_str);
}
END_TEST

START_TEST(test_s21_sprintf_c_indentation_zero_minus) {
#line 392
  char str[100];
  char test_str[100];
  const char format[] = "|This is result: %-10c|";
  char c = 'x';
  ck_assert_int_eq(s21_sprintf(str, format, c), sprintf(test_str, format, c));
  ck_assert_str_eq(str, test_str);
}
END_TEST

START_TEST(test_s21_sprintf_c_indentation_zero_without_sign) {
#line 400
  char str[100];
  char test_str[100];
  const char format[] = "|This is result: %10c|";
  char c = 'x';
  ck_assert_int_eq(s21_sprintf(str, format, c), sprintf(test_str, format, c));
  ck_assert_str_eq(str, test_str);
}
END_TEST

START_TEST(test_s21_sprintf_c_point) {
#line 408
  char str[100];
  char test_str[100];
  const char format[] = "|This is result: %c|";
  char c = 'x';
  ck_assert_int_eq(s21_sprintf(str, format, c), sprintf(test_str, format, c));
  ck_assert_str_eq(str, test_str);
}
END_TEST

START_TEST(test_s21_sprintf_c_point_with_precision) {
#line 416
  char str[100];
  char test_str[100];
  const char format[] = "|This is result: %3c|";
  char c = 'x';
  ck_assert_int_eq(s21_sprintf(str, format, c), sprintf(test_str, format, c));
  ck_assert_str_eq(str, test_str);
}
END_TEST

START_TEST(test_s21_sprintf_d_positive) {
#line 424
  char str[100];
  char test_str[100];
  const char format[] = "|This is result: %d|";
  int d = 567;
  ck_assert_int_eq(s21_sprintf(str, format, d), sprintf(test_str, format, d));
  ck_assert_str_eq(str, test_str);
}
END_TEST

START_TEST(test_s21_sprintf_d_negative) {
#line 432
  char str[100];
  char test_str[100];
  const char format[] = "|This is result: %d|";
  int d = -567;
  ck_assert_int_eq(s21_sprintf(str, format, d), sprintf(test_str, format, d));
  ck_assert_str_eq(str, test_str);
}
END_TEST

START_TEST(test_s21_sprintf_d_positive_with_plus) {
#line 440
  char str[100];
  char test_str[100];
  const char format[] = "|This is result: %+d|";
  int d = 567;
  ck_assert_int_eq(s21_sprintf(str, format, d), sprintf(test_str, format, d));
  ck_assert_str_eq(str, test_str);
}
END_TEST

START_TEST(test_s21_sprintf_d_negative_with_plus) {
#line 448
  char str[100];
  char test_str[100];
  const char format[] = "|This is result: %+d|";
  int d = -567;
  ck_assert_int_eq(s21_sprintf(str, format, d), sprintf(test_str, format, d));
  ck_assert_str_eq(str, test_str);
}
END_TEST

START_TEST(test_s21_sprintf_d_positive_with_space) {
#line 456
  char str[100];
  char test_str[100];
  const char format[] = "|This is result: % d|";
  int d = 567;
  ck_assert_int_eq(s21_sprintf(str, format, d), sprintf(test_str, format, d));
  ck_assert_str_eq(str, test_str);
}
END_TEST

START_TEST(test_s21_sprintf_d_negative_with_space) {
#line 464
  char str[100];
  char test_str[100];
  const char format[] = "|This is result: % d|";
  int d = 567;
  ck_assert_int_eq(s21_sprintf(str, format, d), sprintf(test_str, format, d));
  ck_assert_str_eq(str, test_str);
}
END_TEST

START_TEST(test_s21_sprintf_d_left_intend_space) {
#line 472
  char str[100];
  char test_str[100];
  const char format[] = "|This is result: %+10d|";
  int d = 567;
  ck_assert_int_eq(s21_sprintf(str, format, d), sprintf(test_str, format, d));
  ck_assert_str_eq(str, test_str);
}
END_TEST

START_TEST(test_s21_sprintf_d_rigth_intend_space) {
#line 480
  char str[100];
  char test_str[100];
  const char format[] = "|This is result: %-10d|";
  int d = 567;
  ck_assert_int_eq(s21_sprintf(str, format, d), sprintf(test_str, format, d));
  ck_assert_str_eq(str, test_str);
}
END_TEST

START_TEST(test_s21_sprintf_negative_d_rigth_intend_space) {
#line 488
  char str[100];
  char test_str[100];
  const char format[] = "|This is result: %-10d|";
  int d = -567;
  ck_assert_int_eq(s21_sprintf(str, format, d), sprintf(test_str, format, d));
  ck_assert_str_eq(str, test_str);
}
END_TEST

START_TEST(test_s21_sprintf_negative_d_left_intend_space) {
#line 496
  char str[100];
  char test_str[100];
  const char format[] = "|This is result: %+10d|";
  int d = -567;
  ck_assert_int_eq(s21_sprintf(str, format, d), sprintf(test_str, format, d));
  ck_assert_str_eq(str, test_str);
}
END_TEST

START_TEST(test_s21_sprintf_d_left_intend_zero) {
#line 504
  char str[100];
  char test_str[100];
  const char format[] = "|This is result: %010d|";
  int d = 567;
  ck_assert_int_eq(s21_sprintf(str, format, d), sprintf(test_str, format, d));
  ck_assert_str_eq(str, test_str);
}
END_TEST

START_TEST(test_s21_sprintf_d_try_rigth_intend_zero) {
#line 512
  char str[100];
  char test_str[100];
  const char format[] = "|This is result: %010d|";
  int d = 567;
  ck_assert_int_eq(s21_sprintf(str, format, d), sprintf(test_str, format, d));
  ck_assert_str_eq(str, test_str);
}
END_TEST

START_TEST(test_s21_sprintf_negative_d_try_rigth_intend_zero) {
#line 520
  char str[100];
  char test_str[100];
  const char format[] = "|This is result: %-10d|";
  int d = -567;
  ck_assert_int_eq(s21_sprintf(str, format, d), sprintf(test_str, format, d));
  ck_assert_str_eq(str, test_str);
}
END_TEST

START_TEST(test_s21_sprintf_negative_d_left_intend_zero) {
#line 528
  char str[100];
  char test_str[100];
  const char format[] = "|This is result: %+10d|";
  int d = -567;
  ck_assert_int_eq(s21_sprintf(str, format, d), sprintf(test_str, format, d));
  ck_assert_str_eq(str, test_str);
}
END_TEST

START_TEST(test_s21_sprintf_zero_point_with_d) {
#line 536
  char str[100];
  char test_str[100];
  const char format[] = "|This is result: %.d|";
  int d = 0;
  ck_assert_int_eq(s21_sprintf(str, format, d), sprintf(test_str, format, d));
  ck_assert_str_eq(str, test_str);

#ifdef __APPLE__
}
END_TEST

START_TEST(test_s21_sprintf_width_zero_point_with_d) {
#line 545
  char str[100];
  char test_str[100];
  const char format[] = "|This is result: %010.d|";
  int d = 0;
  ck_assert_int_eq(s21_sprintf(str, format, d), sprintf(test_str, format, d));
  ck_assert_str_eq(str, test_str);
#endif
}
END_TEST

START_TEST(test_s21_sprintf_zero_point_with_d_and_plus) {
#line 554
  char str[100];
  char test_str[100];
  const char format[] = "|This is result: %+.d|";
  int d = 0;
  ck_assert_int_eq(s21_sprintf(str, format, d), sprintf(test_str, format, d));
  ck_assert_str_eq(str, test_str);
}
END_TEST

START_TEST(test_s21_sprintf_hd) {
#line 562
  char str[100];
  char test_str[100];
  const char format[] = "|This is result: %hd|";
  short int hd = 32767;
  ck_assert_int_eq(s21_sprintf(str, format, hd), sprintf(test_str, format, hd));
  ck_assert_str_eq(str, test_str);
}
END_TEST

START_TEST(test_s21_sprintf_ld) {
#line 570
  char str[100];
  char test_str[100];
  const char format[] = "|This is result: %ld|";
  long ld = -8446744073709551610L;
  ck_assert_int_eq(s21_sprintf(str, format, ld), sprintf(test_str, format, ld));
  ck_assert_str_eq(str, test_str);
}
END_TEST

START_TEST(test_s21_sprintf_u) {
#line 578
  char str[100];
  char test_str[100];
  const char format[] = "|This is result: %u|";
  unsigned int u = 4294967295U;
  ck_assert_int_eq(s21_sprintf(str, format, u), sprintf(test_str, format, u));
  ck_assert_str_eq(str, test_str);
}
END_TEST

START_TEST(test_s21_sprintf_hu) {
#line 586
  char str[100];
  char test_str[100];
  const char format[] = "|This is result: %hu|";
  unsigned short int hu = 32767;
  ck_assert_int_eq(s21_sprintf(str, format, hu), sprintf(test_str, format, hu));
  ck_assert_str_eq(str, test_str);
}
END_TEST

START_TEST(test_s21_sprintf_lu) {
#line 594
  char str[100];
  char test_str[100];
  const char format[] = "|This is result: %lu|";
  unsigned long int lu = 18446744073709551615UL;
  ck_assert_int_eq(s21_sprintf(str, format, lu), sprintf(test_str, format, lu));
  ck_assert_str_eq(str, test_str);
}
END_TEST

START_TEST(test_s21_sprintf_o_normal) {
#line 602
  char str[100];
  char test_str[100];
  const char format[] = "|This is result: %o|";
  int d = 102567;
  ck_assert_int_eq(s21_sprintf(str, format, d), sprintf(test_str, format, d));
  ck_assert_str_eq(str, test_str);
}
END_TEST

START_TEST(test_s21_sprintf_o_with_prefix) {
#line 610
  char str[100];
  char test_str[100];
  const char format[] = "|This is result: %#o|";
  int d = 102567;
  ck_assert_int_eq(s21_sprintf(str, format, d), sprintf(test_str, format, d));
  ck_assert_str_eq(str, test_str);
}
END_TEST

START_TEST(test_s21_sprintf_o_zero_with_sharp) {
#line 618
  char str[100];
  char test_str[100];
  const char format[] = "|This is result: %#o|";
  int d = 0;
  ck_assert_int_eq(s21_sprintf(str, format, d), sprintf(test_str, format, d));
  ck_assert_str_eq(str, test_str);
}
END_TEST

START_TEST(test_s21_sprintf_o_zero_point_with_sharp) {
#line 626
  char str[100];
  char test_str[100];
  const char format[] = "|This is result: %#.o|";
  int d = 0;
  ck_assert_int_eq(s21_sprintf(str, format, d), sprintf(test_str, format, d));
  ck_assert_str_eq(str, test_str);

#ifdef __APPLE__
}
END_TEST

START_TEST(test_s21_sprintf_o_zero_point_with_sharp_and_width) {
#line 635
  char str[100];
  char test_str[100];
  const char format[] = "|This is result: %#010.o|";
  int d = 0;
  ck_assert_int_eq(s21_sprintf(str, format, d), sprintf(test_str, format, d));
  ck_assert_str_eq(str, test_str);
}
END_TEST

START_TEST(test_s21_sprintf_o_zero_point_with_sharp_and_width_and_plus) {
#line 643
  char str[100];
  char test_str[100];
  const char format[] = "|This is result: %#010.o|";
  int d = 0;
  ck_assert_int_eq(s21_sprintf(str, format, d), sprintf(test_str, format, d));
  ck_assert_str_eq(str, test_str);
}
END_TEST

START_TEST(test_s21_sprintf_o_zero_point_with_sharp_and_width_and_minus) {
#line 651
  char str[100];
  char test_str[100];
  const char format[] = "|This is result: %#010.o|";
  int d = 0;
  ck_assert_int_eq(s21_sprintf(str, format, d), sprintf(test_str, format, d));
  ck_assert_str_eq(str, test_str);
#endif
}
END_TEST

START_TEST(test_s21_sprintf_x_normal) {
#line 660
  char str[100];
  char test_str[100];
  const char format[] = "|This is result: %x|";
  int d = 102567;
  ck_assert_int_eq(s21_sprintf(str, format, d), sprintf(test_str, format, d));
  ck_assert_str_eq(str, test_str);
}
END_TEST

START_TEST(test_s21_sprintf_X_normal) {
#line 668
  char str[100];
  char test_str[100];
  const char format[] = "|This is result: %X|";
  int d = 102567;
  ck_assert_int_eq(s21_sprintf(str, format, d), sprintf(test_str, format, d));
  ck_assert_str_eq(str, test_str);
}
END_TEST

START_TEST(test_s21_sprintf_x_with_prefix) {
#line 676
  char str[100];
  char test_str[100];
  const char format[] = "|This is result: %#x|";
  int d = 102567;
  ck_assert_int_eq(s21_sprintf(str, format, d), sprintf(test_str, format, d));
  ck_assert_str_eq(str, test_str);
}
END_TEST

START_TEST(test_s21_sprintf_X_with_prefix) {
#line 684
  char str[100];
  char test_str[100];
  const char format[] = "|This is result: %#X|";
  int d = 102567;
  ck_assert_int_eq(s21_sprintf(str, format, d), sprintf(test_str, format, d));
  ck_assert_str_eq(str, test_str);
}
END_TEST

START_TEST(test_s21_sprintf_x_zero_with_sharp) {
#line 692
  char str[100];
  char test_str[100];
  const char format[] = "|This is result: %#x|";
  int d = 0;
  ck_assert_int_eq(s21_sprintf(str, format, d), sprintf(test_str, format, d));
  ck_assert_str_eq(str, test_str);
}
END_TEST

START_TEST(test_s21_sprintf_x_zero_point_with_sharp) {
#line 700
  char str[100];
  char test_str[100];
  const char format[] = "|This is result: %#.x|";
  int d = 0;
  ck_assert_int_eq(s21_sprintf(str, format, d), sprintf(test_str, format, d));
  ck_assert_str_eq(str, test_str);
}
END_TEST

START_TEST(test_s21_sprintf_x_width_sharp) {
#line 708
  char str[100];
  char test_str[100];
  const char format[] = "|This is result: %#020x|";
  int d = 102345;
  ck_assert_int_eq(s21_sprintf(str, format, d), sprintf(test_str, format, d));
  ck_assert_str_eq(str, test_str);

#ifdef __APPLE__
}
END_TEST

START_TEST(test_s21_sprintf_x_zero_point_with_sharp_and_width) {
#line 717
  char str[100];
  char test_str[100];
  const char format[] = "|This is result: %#010.x|";
  int d = 0;
  ck_assert_int_eq(s21_sprintf(str, format, d), sprintf(test_str, format, d));
  ck_assert_str_eq(str, test_str);
}
END_TEST

START_TEST(test_s21_sprintf_x_zero_point_with_sharp_and_width_and_plus) {
#line 725
  char str[100];
  char test_str[100];
  const char format[] = "|This is result: %#010.x|";
  int d = 0;
  ck_assert_int_eq(s21_sprintf(str, format, d), sprintf(test_str, format, d));
  ck_assert_str_eq(str, test_str);
#endif
}
END_TEST

START_TEST(test_s21_sprintf_x_with_precision) {
#line 734
  char str[100];
  char test_str[100];
  const char format[] = "|This is result: %#.20x";
  int d = 102567;
  ck_assert_int_eq(s21_sprintf(str, format, d), sprintf(test_str, format, d));
  ck_assert_str_eq(str, test_str);

#ifdef __APPLE__
}
END_TEST

START_TEST(test_s21_sprintf_x_point_width) {
#line 743
  char str[100];
  char test_str[100];
  const char format[] = "|This is result: %010.x|";
  int d = 102567;
  ck_assert_int_eq(s21_sprintf(str, format, d), sprintf(test_str, format, d));
  ck_assert_str_eq(str, test_str);
#endif
}
END_TEST

START_TEST(test_s21_sprintf_p) {
#line 752
  char str[100];
  char test_str[100];
  const char format[] = "|This is result: %p|";
  int d = 102567;
  ck_assert_int_eq(s21_sprintf(str, format, &d), sprintf(test_str, format, &d));
  ck_assert_str_eq(str, test_str);
}
END_TEST

START_TEST(test_s21_sprintf_positive_lf_with_zero_intend_and_round) {
#line 761
  char str[100];
  char test_str[100];
  const char format[] = "This is result %010.2lf|";
  double lf = 2.999995945555;
  ck_assert_int_eq(s21_sprintf(str, format, lf), sprintf(test_str, format, lf));
  ck_assert_str_eq(str, test_str);
}
END_TEST

START_TEST(test_s21_sprintf_double_less_one) {
#line 769
  char str[100];
  char test_str[100];
  const char format[] = "This is result %lf|";
  double lf = 0.0032;
  ck_assert_int_eq(s21_sprintf(str, format, lf), sprintf(test_str, format, lf));
  ck_assert_str_eq(str, test_str);
}
END_TEST

START_TEST(test_s21_sprintf_double_less_one_precision_2) {
#line 777
  char str[100];
  char test_str[100];
  const char format[] = "This is result %.2lf|";
  double lf = 0.0032;
  ck_assert_int_eq(s21_sprintf(str, format, lf), sprintf(test_str, format, lf));
  ck_assert_str_eq(str, test_str);
}
END_TEST

START_TEST(test_s21_sprintf_double_less_one__negative_precision_2) {
#line 785
  char str[100];
  char test_str[100];
  const char format[] = "This is result %.2lf|";
  double lf = -0.0032;
  ck_assert_int_eq(s21_sprintf(str, format, lf), sprintf(test_str, format, lf));
  ck_assert_str_eq(str, test_str);
}
END_TEST

START_TEST(test_s21_sprintf_positive__with_plus_lf_with_zero_intend_and_round) {
#line 793
  char str[100];
  char test_str[100];
  const char format[] = "This is result %+010.2lf|";
  double lf = 2.999995945555;
  ck_assert_int_eq(s21_sprintf(str, format, lf), sprintf(test_str, format, lf));
  ck_assert_str_eq(str, test_str);
}
END_TEST

START_TEST(test_s21_sprintf_negative_lf_with_zero_intend_and_round) {
#line 801
  char str[100];
  char test_str[100];
  const char format[] = "This is result %010.2lf|";
  double lf = -2.999995945555;
  ck_assert_int_eq(s21_sprintf(str, format, lf), sprintf(test_str, format, lf));
  ck_assert_str_eq(str, test_str);
}
END_TEST

START_TEST(test_s21_sprintf_lf_without_frac_prcision_zero) {
#line 809
  char str[100];
  char test_str[100];
  const char format[] = "This is result %.lf|";
  double lf = 7;
  ck_assert_int_eq(s21_sprintf(str, format, lf), sprintf(test_str, format, lf));
  ck_assert_str_eq(str, test_str);
}
END_TEST

START_TEST(test_s21_sprintf_long_double) {
#line 817
  char str[100];
  char test_str[100];
  const char format[] = "This is result %.10Lf|";
  long double lf = 123.3948503984593;
  ck_assert_int_eq(s21_sprintf(str, format, lf), sprintf(test_str, format, lf));
  ck_assert_str_eq(str, test_str);
}
END_TEST

START_TEST(test_s21_sprintf_lf_without_frac_with_sharp) {
#line 825
  char str[100];
  char test_str[100];
  const char format[] = "This is result %#.lf|";
  double lf = 7;
  ck_assert_int_eq(s21_sprintf(str, format, lf), sprintf(test_str, format, lf));
  ck_assert_str_eq(str, test_str);
}
END_TEST

START_TEST(test_s21_sprintf_lf_with_star) {
#line 833
  char str[100];
  char test_str[100];
  const char format[] = "This is result %.*lf|";
  double lf = 7.23456;
  int prec = 2;
  ck_assert_int_eq(s21_sprintf(str, format, prec, lf),
                   sprintf(test_str, format, prec, lf));
  ck_assert_str_eq(str, test_str);
}
END_TEST

START_TEST(test_s21_sprintf_lf_with_two_star) {
#line 842
  char str[100];
  char test_str[100];
  const char format[] = "This is result %*.*lf|";
  double lf = 7.23456;
  int prec = 2;
  int wid = 10;
  ck_assert_int_eq(s21_sprintf(str, format, wid, prec, lf),
                   sprintf(test_str, format, wid, prec, lf));
  ck_assert_str_eq(str, test_str);
}
END_TEST

START_TEST(test_s21_sprintf_e) {
#line 852
  char str[100];
  char test_str[100];
  const char format[] = "This is result %e|";
  double for_e = -0.000032;
  ck_assert_int_eq(s21_sprintf(str, format, for_e),
                   sprintf(test_str, format, for_e));
  ck_assert_str_eq(str, test_str);
}
END_TEST

START_TEST(test_s21_sprintf_e_with_precision) {
#line 860
  char str[100];
  char test_str[100];
  const char format[] = "This is result %.3e|";
  double for_e = -0.000032;
  ck_assert_int_eq(s21_sprintf(str, format, for_e),
                   sprintf(test_str, format, for_e));
  ck_assert_str_eq(str, test_str);
}
END_TEST

START_TEST(test_s21_sprintf_e_with_null_precision) {
#line 868
  char str[100];
  char test_str[100];
  const char format[] = "This is result %.e|";
  double for_e = -0.000032;
  ck_assert_int_eq(s21_sprintf(str, format, for_e),
                   sprintf(test_str, format, for_e));
  ck_assert_str_eq(str, test_str);
}
END_TEST

START_TEST(test_s21_sprintf_e_with_null_precision_sharp) {
#line 876
  char str[100];
  char test_str[100];
  const char format[] = "This is result %#.e|";
  double for_e = -0.000032;
  ck_assert_int_eq(s21_sprintf(str, format, for_e),
                   sprintf(test_str, format, for_e));
  ck_assert_str_eq(str, test_str);
}
END_TEST

START_TEST(test_s21_sprintf_e_whole) {
#line 884
  char str[100];
  char test_str[100];
  const char format[] = "This is result %e|";
  double for_e = 3.0;
  ck_assert_int_eq(s21_sprintf(str, format, for_e),
                   sprintf(test_str, format, for_e));
  ck_assert_str_eq(str, test_str);
}
END_TEST

START_TEST(test_s21_sprintf_e_almost_null) {
#line 892
  char str[100];
  char test_str[100];
  const char format[] = "This is result %e|";
  double for_e = 0.00001;
  ck_assert_int_eq(s21_sprintf(str, format, for_e),
                   sprintf(test_str, format, for_e));
  ck_assert_str_eq(str, test_str);
}
END_TEST

START_TEST(test_s21_sprintf_e_big) {
#line 900
  char str[100];
  char test_str[100];
  const char format[] = "This is result %e|";
  double for_e = 12345678987.02;
  ck_assert_int_eq(s21_sprintf(str, format, for_e),
                   sprintf(test_str, format, for_e));
  ck_assert_str_eq(str, test_str);
}
END_TEST

START_TEST(test_s21_sprintf_string) {
#line 908
  char str[100];
  char test_str[100];
  const char format[] = "This is result %s|";
  char *s = "string";
  ck_assert_int_eq(s21_sprintf(str, format, s), sprintf(test_str, format, s));
  ck_assert_str_eq(str, test_str);
}
END_TEST

START_TEST(test_s21_sprintf_string_precision) {
#line 916
  char str[100];
  char test_str[100];
  const char format[] = "This is result %.3s|";
  char *s = "string";
  ck_assert_int_eq(s21_sprintf(str, format, s), sprintf(test_str, format, s));
  ck_assert_str_eq(str, test_str);
}
END_TEST

START_TEST(test_s21_sprintf_string_width_space) {
#line 924
  char str[100];
  char test_str[100];
  const char format[] = "This is result %10s|";
  char *s = "string";
  ck_assert_int_eq(s21_sprintf(str, format, s), sprintf(test_str, format, s));
  ck_assert_str_eq(str, test_str);
}
END_TEST

START_TEST(test_s21_sprintf_string_width_rigth) {
#line 932
  char str[100];
  char test_str[100];
  const char format[] = "This is result %-10s|";
  char *s = "string";
  ck_assert_int_eq(s21_sprintf(str, format, s), sprintf(test_str, format, s));
  ck_assert_str_eq(str, test_str);
}
END_TEST

START_TEST(test_s21_sprintf_string_width_precision) {
#line 940
  char str[100];
  char test_str[100];
  const char format[] = "This is result %10.3s|";
  char *s = "string";
  ck_assert_int_eq(s21_sprintf(str, format, s), sprintf(test_str, format, s));
  ck_assert_str_eq(str, test_str);
}
END_TEST

START_TEST(test_s21_sprintf_g_1) {
#line 948
  char str[100];
  char test_str[100];
  const char format[] = "This is result %g|";
  double f = 123.12;
  ck_assert_int_eq(s21_sprintf(str, format, f), sprintf(test_str, format, f));
  ck_assert_str_eq(str, test_str);
}
END_TEST

START_TEST(test_s21_sprintf_g_2) {
#line 956
  char str[100];
  char test_str[100];
  const char format[] = "This is result %g|";
  double f = 123.123456;
  ck_assert_int_eq(s21_sprintf(str, format, f), sprintf(test_str, format, f));
  ck_assert_str_eq(str, test_str);
}
END_TEST

START_TEST(test_s21_sprintf_g_3) {
#line 964
  char str[100];
  char test_str[100];
  const char format[] = "This is result %g|";
  double f = 123456.123;
  ck_assert_int_eq(s21_sprintf(str, format, f), sprintf(test_str, format, f));
  ck_assert_str_eq(str, test_str);
}
END_TEST

START_TEST(test_s21_sprintf_g_4) {
#line 972
  char str[100];
  char test_str[100];
  const char format[] = "This is result %G|";
  double f = 132.9873458903;
  ck_assert_int_eq(s21_sprintf(str, format, f), sprintf(test_str, format, f));
  ck_assert_str_eq(str, test_str);
}
END_TEST

START_TEST(test_s21_sprintf_g_5) {
#line 980
  char str[100];
  char test_str[100];
  const char format[] = "This is result %#.G|";
  double f = -0.000032;
  ck_assert_int_eq(s21_sprintf(str, format, f), sprintf(test_str, format, f));
  ck_assert_str_eq(str, test_str);
}
END_TEST

START_TEST(test_s21_sprintf_g_whole_without_sharp) {
#line 988
  char str[100];
  char test_str[100];
  const char format[] = "This is result %.g|";
  double f = 3.0;
  ck_assert_int_eq(s21_sprintf(str, format, f), sprintf(test_str, format, f));
  ck_assert_str_eq(str, test_str);
}
END_TEST

START_TEST(test_s21_sprintf_g_whole_with_sharp) {
#line 996
  char str[100];
  char test_str[100];
  const char format[] = "This is result %#.g|";
  double f = 3.0;
  ck_assert_int_eq(s21_sprintf(str, format, f), sprintf(test_str, format, f));
  ck_assert_str_eq(str, test_str);
}
END_TEST

START_TEST(test_s21_sprintf_two_specifiers) {
#line 1004
  char str[100];
  char test_str[100];
  const char format[] = "This is result %d second %s|";
  int d = 15;
  char *s = "string";
  ck_assert_int_eq(s21_sprintf(str, format, d, s),
                   sprintf(test_str, format, d, s));
  ck_assert_str_eq(str, test_str);
}
END_TEST

START_TEST(test_21_sscanf) {
#line 1013
  char *str = "7856 123 +1234567890987654321 2121212121212 123";
  int d1 = 0, d2 = 0, n1 = 0, n2 = 0, count1 = 0, count2 = 0;
  long int ld1 = 0, ld2 = 0;
  short int hd1 = 0, hd2 = 0;
  count1 = s21_sscanf(str, "%*d %d %ld %hd%n", &d1, &ld1, &hd1, &n1);
  count2 = sscanf(str, "%*d %d %ld %hd%n", &d2, &ld2, &hd2, &n2);
  ck_assert_int_eq(d1, d2);
  ck_assert_int_eq(ld1, ld2);
  ck_assert_int_eq(hd1, hd2);
  ck_assert_int_eq(n1, n2);
  ck_assert_int_eq(count1, count2);

  char *str_i = "123 0x65a8bd666 0407461";
  int i1 = 0, i2 = 0;
  long int li1 = 0, li2 = 0;
  short int hi1 = 0, hi2 = 0;
  s21_sscanf(str_i, "%i %li %hi", &i1, &li1, &hi1);
  sscanf(str_i, "%i %li %hi", &i2, &li2, &hi2);
  ck_assert_int_eq(i1, i2);
  ck_assert_int_eq(li1, li2);
  ck_assert_int_eq(hi1, hi2);

  char *ustr = "-9 123456789098765432 6578613 8084";
  unsigned int u1 = 0, u2 = 0;
  long unsigned int lu1 = 0, lu2 = 0;
  short unsigned int hu1 = 0, hu2 = 0;
  count1 = s21_sscanf(ustr, "%u %lu %hu %*u", &u1, &lu1, &hu1);
  count2 = sscanf(ustr, "%u %lu %hu %*u", &u2, &lu2, &hu2);
  ck_assert_uint_eq(u1, u2);
  ck_assert_uint_eq(lu1, lu2);
  ck_assert_uint_eq(hu1, hu2);
  ck_assert_uint_eq(count1, count2);

  unsigned int o1 = 0, o2 = 0;
  long unsigned int lo1 = 0, lo2 = 0;
  short unsigned int ho1 = 0, ho2 = 0;
  count1 = s21_sscanf(ustr, "%o %lo %ho", &o1, &lo1, &ho1);
  count2 = sscanf(ustr, "%o %lo %ho", &o2, &lo2, &ho2);
  ck_assert_uint_eq(o1, o2);
  ck_assert_uint_eq(lo1, lo2);
  ck_assert_uint_eq(ho1, ho2);
  ck_assert_uint_eq(count1, count2);

  char *str_x = "privet -123abc123 1234567890abcdef0000 abc12345 aaa";
  unsigned int x1 = 0, x2 = 0;
  long unsigned int lx1 = 0, lx2 = 0;
  short unsigned int hx1 = 0, hx2 = 0;
  count1 = s21_sscanf(str_x, "%*s %x %lx %hx %*x", &x1, &lx1, &hx1);
  count2 = sscanf(str_x, "%*s %x %lx %hx %*x", &x2, &lx2, &hx2);
  ck_assert_int_eq(x1, x2);
  ck_assert_int_eq(lx1, lx2);
  ck_assert_int_eq(hx1, hx2);
  ck_assert_int_eq(count1, count2);

  char *str2 = "! assadaker";
  char c1, c2;
  char cc1[10] = "qq";
  char cc2[10] = "qq";

  s21_sscanf(str2, "%c %s", &c1, cc1);
  sscanf(str2, "%c %s", &c2, cc2);
  ck_assert_int_eq(c1, c2);
  ck_assert_str_eq(cc1, cc2);
  s21_sscanf(str2, "%*c %3s", cc1);
  sscanf(str2, "%*c %3s", cc2);
  ck_assert_str_eq(cc1, cc2);

  char *str3 = "3.14 123456.123456 12345678987654321.1234567890987654321 300";
  char *str4 = "12e7 12e-7 12e+7";
  char *str5 = "1.5e+2 3.14";
  float fl1 = 0, fl2 = 0;
  double db1 = 0, db2 = 0;
  long double ldb1 = 0, ldb2 = 0;

  s21_sscanf(str3, "%f %lf %Lf %*f", &fl1, &db1, &ldb1);
  sscanf(str3, "%f %lf %Lf %*f", &fl2, &db2, &ldb2);
  ck_assert_float_eq(fl1, fl2);
  ck_assert_double_eq(db1, db2);
  ck_assert_ldouble_eq(ldb1, ldb2);
  s21_sscanf(str4, "%e %lE %Le", &fl1, &db1, &ldb1);
  sscanf(str4, "%e %lE %Le", &fl2, &db2, &ldb2);
  ck_assert_float_eq(fl1, fl2);
  ck_assert_double_eq(db1, db2);
  ck_assert_ldouble_eq(ldb1, ldb2);

  s21_sscanf(str5, "%g %lg", &fl1, &db1);
  sscanf(str5, "%g %lg", &fl2, &db2);

  char *str_p = "aaa 1a2b3c\n123456789abcdef";
  void *ptr1 = "a";
  void *ptr2 = "a";
  void *ptr3 = "a";
  void *ptr4 = "a";

  s21_sscanf(str_p, "%*p %p %p", &ptr1, &ptr3);
  sscanf(str_p, "%*p %p %p", &ptr2, &ptr4);
  ck_assert_ptr_eq(ptr1, ptr2);
  ck_assert_ptr_eq(ptr1, ptr2);
}
END_TEST

int main(void) {
  Suite *s1 = suite_create("Core");
  TCase *tc1_1 = tcase_create("Core");
  SRunner *sr = srunner_create(s1);
  int nf;

  suite_add_tcase(s1, tc1_1);
  tcase_add_test(tc1_1, test_s21_memchr);
  tcase_add_test(tc1_1, test_s21_memcmp);
  tcase_add_test(tc1_1, test_s21_memcpy);
  tcase_add_test(tc1_1, test_s21_memset);
  tcase_add_test(tc1_1, test_s21_strncat);
  tcase_add_test(tc1_1, test_s21_strchr);
  tcase_add_test(tc1_1, test_s21_strncmp);
  tcase_add_test(tc1_1, test_s21_strncpy);
  tcase_add_test(tc1_1, test_s21_strcspn);
  tcase_add_test(tc1_1, test_s21_strlen);
  tcase_add_test(tc1_1, test_s21_strerror);
  tcase_add_test(tc1_1, test_s21_strpbrk);
  tcase_add_test(tc1_1, test_s21_strrchr);
  tcase_add_test(tc1_1, test_s21_strstr);
  tcase_add_test(tc1_1, test_s21_strtok_normal);
  tcase_add_test(tc1_1, test_s21_strtok_empty_delim);
  tcase_add_test(tc1_1, test_s21_strtok_empty_str);
  tcase_add_test(tc1_1, test_s21_strtok_delim_in_end);
  tcase_add_test(tc1_1, test_s21_strtok_delim_in_start);
  tcase_add_test(tc1_1, test_s21_strtok_delim_not_match);
  tcase_add_test(tc1_1, test_s21_to_upper);
  tcase_add_test(tc1_1, test_s21_to_lower);
  tcase_add_test(tc1_1, test_s21_insert);
  tcase_add_test(tc1_1, test_s21_trim);
  tcase_add_test(tc1_1, test_s21_sprinf_percent);
  tcase_add_test(tc1_1, test_s21_sprintf_only_c);
  tcase_add_test(tc1_1, test_s21_sprintf_c_with_minus);
  tcase_add_test(tc1_1, test_s21_sprintf_c_indentation_space_plus);
  tcase_add_test(tc1_1, test_s21_sprintf_c_indentation_space_minus);
  tcase_add_test(tc1_1, test_s21_sprintf_c_indentation_zero_minus);
  tcase_add_test(tc1_1, test_s21_sprintf_c_indentation_zero_without_sign);
  tcase_add_test(tc1_1, test_s21_sprintf_c_point);
  tcase_add_test(tc1_1, test_s21_sprintf_c_point_with_precision);
  tcase_add_test(tc1_1, test_s21_sprintf_d_positive);
  tcase_add_test(tc1_1, test_s21_sprintf_d_negative);
  tcase_add_test(tc1_1, test_s21_sprintf_d_positive_with_plus);
  tcase_add_test(tc1_1, test_s21_sprintf_d_negative_with_plus);
  tcase_add_test(tc1_1, test_s21_sprintf_d_positive_with_space);
  tcase_add_test(tc1_1, test_s21_sprintf_d_negative_with_space);
  tcase_add_test(tc1_1, test_s21_sprintf_d_left_intend_space);
  tcase_add_test(tc1_1, test_s21_sprintf_d_rigth_intend_space);
  tcase_add_test(tc1_1, test_s21_sprintf_negative_d_rigth_intend_space);
  tcase_add_test(tc1_1, test_s21_sprintf_negative_d_left_intend_space);
  tcase_add_test(tc1_1, test_s21_sprintf_d_left_intend_zero);
  tcase_add_test(tc1_1, test_s21_sprintf_d_try_rigth_intend_zero);
  tcase_add_test(tc1_1, test_s21_sprintf_negative_d_try_rigth_intend_zero);
  tcase_add_test(tc1_1, test_s21_sprintf_negative_d_left_intend_zero);
  tcase_add_test(tc1_1, test_s21_sprintf_zero_point_with_d);
#ifdef __APPLE__
  tcase_add_test(tc1_1, test_s21_sprintf_width_zero_point_with_d);
#endif
  tcase_add_test(tc1_1, test_s21_sprintf_zero_point_with_d_and_plus);
  tcase_add_test(tc1_1, test_s21_sprintf_hd);
  tcase_add_test(tc1_1, test_s21_sprintf_ld);
  tcase_add_test(tc1_1, test_s21_sprintf_u);
  tcase_add_test(tc1_1, test_s21_sprintf_hu);
  tcase_add_test(tc1_1, test_s21_sprintf_lu);
  tcase_add_test(tc1_1, test_s21_sprintf_o_normal);
  tcase_add_test(tc1_1, test_s21_sprintf_o_with_prefix);
  tcase_add_test(tc1_1, test_s21_sprintf_o_zero_with_sharp);
  tcase_add_test(tc1_1, test_s21_sprintf_o_zero_point_with_sharp);
#ifdef __APPLE__
  tcase_add_test(tc1_1, test_s21_sprintf_o_zero_point_with_sharp_and_width);
  tcase_add_test(tc1_1,
                 test_s21_sprintf_o_zero_point_with_sharp_and_width_and_plus);
  tcase_add_test(tc1_1,
                 test_s21_sprintf_o_zero_point_with_sharp_and_width_and_minus);
#endif
  tcase_add_test(tc1_1, test_s21_sprintf_x_normal);
  tcase_add_test(tc1_1, test_s21_sprintf_X_normal);
  tcase_add_test(tc1_1, test_s21_sprintf_x_with_prefix);
  tcase_add_test(tc1_1, test_s21_sprintf_X_with_prefix);
  tcase_add_test(tc1_1, test_s21_sprintf_x_zero_with_sharp);
  tcase_add_test(tc1_1, test_s21_sprintf_x_zero_point_with_sharp);
#ifdef __APPLE__
  tcase_add_test(tc1_1, test_s21_sprintf_x_zero_point_with_sharp_and_width);
#endif
  tcase_add_test(tc1_1, test_s21_sprintf_x_width_sharp);
#ifdef __APPLE__
  tcase_add_test(tc1_1,
                 test_s21_sprintf_x_zero_point_with_sharp_and_width_and_plus);
#endif
  tcase_add_test(tc1_1, test_s21_sprintf_x_with_precision);
#ifdef __APPLE__
  tcase_add_test(tc1_1, test_s21_sprintf_x_point_width);
#endif
  tcase_add_test(tc1_1, test_s21_sprintf_p);
  tcase_add_test(tc1_1,
                 test_s21_sprintf_positive_lf_with_zero_intend_and_round);
  tcase_add_test(tc1_1, test_s21_sprintf_double_less_one);
  tcase_add_test(tc1_1, test_s21_sprintf_double_less_one_precision_2);
  tcase_add_test(tc1_1, test_s21_sprintf_double_less_one__negative_precision_2);
  tcase_add_test(
      tc1_1,
      test_s21_sprintf_positive__with_plus_lf_with_zero_intend_and_round);
  tcase_add_test(tc1_1,
                 test_s21_sprintf_negative_lf_with_zero_intend_and_round);
  tcase_add_test(tc1_1, test_s21_sprintf_lf_without_frac_prcision_zero);
  tcase_add_test(tc1_1, test_s21_sprintf_long_double);
  tcase_add_test(tc1_1, test_s21_sprintf_lf_without_frac_with_sharp);
  tcase_add_test(tc1_1, test_s21_sprintf_lf_with_star);
  tcase_add_test(tc1_1, test_s21_sprintf_lf_with_two_star);
  tcase_add_test(tc1_1, test_s21_sprintf_e);
  tcase_add_test(tc1_1, test_s21_sprintf_e_with_precision);
  tcase_add_test(tc1_1, test_s21_sprintf_e_with_null_precision);
  tcase_add_test(tc1_1, test_s21_sprintf_e_with_null_precision_sharp);
  tcase_add_test(tc1_1, test_s21_sprintf_e_whole);
  tcase_add_test(tc1_1, test_s21_sprintf_e_almost_null);
  tcase_add_test(tc1_1, test_s21_sprintf_e_big);
  tcase_add_test(tc1_1, test_s21_sprintf_string);
  tcase_add_test(tc1_1, test_s21_sprintf_string_precision);
  tcase_add_test(tc1_1, test_s21_sprintf_string_width_space);
  tcase_add_test(tc1_1, test_s21_sprintf_string_width_rigth);
  tcase_add_test(tc1_1, test_s21_sprintf_string_width_precision);
  tcase_add_test(tc1_1, test_s21_sprintf_g_1);
  tcase_add_test(tc1_1, test_s21_sprintf_g_2);
  tcase_add_test(tc1_1, test_s21_sprintf_g_3);
  tcase_add_test(tc1_1, test_s21_sprintf_g_4);
  tcase_add_test(tc1_1, test_s21_sprintf_g_5);
  tcase_add_test(tc1_1, test_s21_sprintf_g_whole_without_sharp);
  tcase_add_test(tc1_1, test_s21_sprintf_g_whole_with_sharp);
  tcase_add_test(tc1_1, test_s21_sprintf_two_specifiers);
  tcase_add_test(tc1_1, test_21_sscanf);

  srunner_run_all(sr, CK_ENV);
  nf = srunner_ntests_failed(sr);
  srunner_free(sr);

  return nf == 0 ? 0 : 1;
}
